from pathlib import Path


# OpenVPN
OPENVPN_DIR = Path("/etc/openvpn")
OPENVPN_SERVER_DIR = OPENVPN_DIR / "server"
OPENVPN_PKI_DIR = OPENVPN_SERVER_DIR / "pki"
OPENVPN_STATUS_LOG_PATH = Path("/run/openvpn-server/status-server.log")
OPENVPN_CLIENT_CONFIGS_DIR = OPENVPN_DIR / "client-configs"
OPENVPN_ENFORCEMENT_HOOK_PATH = OPENVPN_SERVER_DIR / "atlas_enforcement_hook.py"
OPENVPN_AUTH_USER_PASS_SCRIPT_PATH = OPENVPN_SERVER_DIR / "atlas_auth_user_pass.py"
OPENVPN_UPDATE_RESOLV_CONF_PATH = OPENVPN_DIR / "update-resolv-conf"
OPENVPN_ATLAS_DB_PATH = OPENVPN_SERVER_DIR / "atlas.db"
OPENVPN_DEFAULT_MANAGEMENT_HOST = "127.0.0.1"
OPENVPN_DEFAULT_MANAGEMENT_PORT = 5555
OPENVPN_SERVICE_NAME = "openvpn-server@server"
OPENVPN_SERVICE_CANDIDATES = ("openvpn-server@server", "openvpn@server", "openvpn.service")


# WireGuard
WIREGUARD_BASE_DIR = Path("/etc/wireguard")
WIREGUARD_DEFAULT_INTERFACE = "wg0"
WIREGUARD_DEFAULT_WAN_INTERFACE = "eth0"
WIREGUARD_SERVICE_TEMPLATE = "wg-quick@{interface}"
WIREGUARD_DEFAULT_LISTEN_PORT = 51820


# Policy-based routing (PBR)
PBR_RT_TABLES_PATH = Path("/etc/iproute2/rt_tables")
PBR_TABLE_PREFIX = "atlas_pbr"
PBR_COMMENT_PREFIX = "ATLAS_PBR"
PBR_DEFAULT_NAT_COMMENT = "ATLAS_DEFAULT_NAT"
PBR_DEFAULT_WAN_INTERFACE = "eth0"
PBR_DEFAULT_DEST_CIDR = "0.0.0.0/0"
PBR_DEFAULT_PROXY_PROTOCOL = "tcp"
PBR_LEGACY_DNS_REDIRECT_PORT = 5300


# Obfuscation
SQUID_CONFIG_PATH = Path("/etc/squid/squid.conf")
OBFS_OPENVPN_TCP_PORT = 443
OBFS_DEFAULT_PROXY_PORT = 8080
