from pathlib import Path


# OpenVPN
OPENVPN_DIR = Path("/etc/openvpn")
OPENVPN_SERVER_DIR = OPENVPN_DIR / "server"
OPENVPN_PKI_DIR = OPENVPN_SERVER_DIR / "pki"
OPENVPN_STATUS_LOG_PATH = Path("/run/openvpn-server/status-server.log")
OPENVPN_CLIENT_CONFIGS_DIR = OPENVPN_DIR / "client-configs"
OPENVPN_ENFORCEMENT_HOOK_PATH = OPENVPN_SERVER_DIR / "atlas_enforcement_hook.py"
OPENVPN_AUTH_USER_PASS_SCRIPT_PATH = OPENVPN_SERVER_DIR / "atlas_auth_user_pass.py"
OPENVPN_UPDATE_RESOLV_CONF_PATH = OPENVPN_DIR / "update-resolv-conf"
OPENVPN_ATLAS_DB_PATH = OPENVPN_SERVER_DIR / "atlas.db"
OPENVPN_DEFAULT_MANAGEMENT_HOST = "127.0.0.1"
OPENVPN_DEFAULT_MANAGEMENT_PORT = 5555
OPENVPN_SERVICE_NAME = "openvpn-server@server"
OPENVPN_SERVICE_CANDIDATES = ("openvpn-server@server", "openvpn@server", "openvpn.service")


# WireGuard
WIREGUARD_BASE_DIR = Path("/etc/wireguard")
WIREGUARD_DEFAULT_INTERFACE = "wg0"
WIREGUARD_DEFAULT_WAN_INTERFACE = "eth0"
WIREGUARD_SERVICE_TEMPLATE = "wg-quick@{interface}"
WIREGUARD_DEFAULT_LISTEN_PORT = 51820


# Policy-based routing (PBR)
PBR_RT_TABLES_PATH = Path("/etc/iproute2/rt_tables")
PBR_TABLE_PREFIX = "atlas_pbr"
PBR_COMMENT_PREFIX = "ATLAS_PBR"
PBR_DEFAULT_NAT_COMMENT = "ATLAS_DEFAULT_NAT"
PBR_DEFAULT_WAN_INTERFACE = "eth0"
PBR_DEFAULT_DEST_CIDR = "0.0.0.0/0"
PBR_DEFAULT_PROXY_PROTOCOL = "tcp"
PBR_LEGACY_DNS_REDIRECT_PORT = 5300


# Obfuscation
SQUID_CONFIG_PATH = Path("/etc/squid/squid.conf")
OBFS_OPENVPN_TCP_PORT = 443
OBFS_DEFAULT_PROXY_PORT = 8080


# PPP / L2TP
PPP_CHAP_SECRETS_PATH = Path("/etc/ppp/chap-secrets")
PPP_RADATTR_DIR = Path("/var/run")
PPP_INTERFACE_PREFIX = "ppp"
PPP_SESSION_SCAN_COMMAND = ("ip", "-o", "link", "show")
PPP_PS_COMMAND = ("ps", "-eo", "pid,args")
IPSEC_SECRETS_PATH = Path("/etc/ipsec.secrets")
XL2TPD_CONFIG_PATH = Path("/etc/xl2tpd/xl2tpd.conf")
L2TP_DEFAULT_LOCAL_IP = "10.10.11.1"

L2TP_DEFAULT_PORT = 1701
IPSEC_DEFAULT_IKE_PORT = 500
IPSEC_DEFAULT_NATT_PORT = 4500
IPSEC_PSK_ENV_KEY = "ATLAS_IPSEC_PSK"
IPSEC_DEFAULT_PSK = "atlas-change-me-strong-psk"
